# Generated by Django 4.2.14 on 2024-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_superuser',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
