# Generated by Django 4.2.14 on 2024-09-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_userinfo_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
